### ISSUE TITLE
Generate Invoice Payload

### ISSUE THREAD

**Issue by Marcos8060** [PROTO-TYPE-SOLUTIONS/make-easy-hmis#318]
There is an issue with the generate invoice payload structure that the backend expects, I have taken my time to research and look at it:

{
  "item_name": "string",
  "item_price": "-418094.2",
  "invoice_id": 0,
  "service_id": 0
}

The concern is that the front end sends an array since multiple items can be checked but the backend has structured the payload as if only a single item is being submitted.

**Comment by mosesmbadi** [comment]
I believe this was sorted? If not re-open with more info.
